# Generated by Django 5.2.1 on 2025-10-20 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.CharField(choices=[('turno_dia_1', 'Turno Día 1: 7:00 a.m. – 3:00 p.m. (Lun a Vie; Descanso: Sáb y Dom)'), ('turno_dia_2', 'Turno Día 2: 9:00 a.m. – 5:00 p.m. (Mar a Sáb; Descanso: Dom y Lun)'), ('turno_noche_1', 'Turno Noche 1: 3:00 p.m. – 11:00 p.m. (Lun a Vie; Descanso: Sáb y Dom)'), ('turno_noche_2', 'Turno Noche 2: 11:00 p.m. – 7:00 a.m. (Mié a Dom; Descanso: Lun y Mar)')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.TextField()),
                ('contacto', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=150)),
                ('contenido_principal', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('despedida', models.TextField(default='Atentamente')),
                ('firma', models.TextField(default='Clínica G1')),
                ('informacion_contacto', models.TextField(default='Contacto: 12345678')),
                ('saludo', models.TextField(default='Estimado/a')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Médico', 'Médico'), ('Recepcionista', 'Recepcionista'), ('Paciente', 'Paciente')], max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('reminder_sent_24', models.BooleanField(default=False)),
                ('reminder_sent_48', models.BooleanField(default=False)),
                ('reprogramaciones_total', models.PositiveIntegerField(default=0)),
                ('cita_origen', models.ForeignKey(blank=True, help_text='Si esta cita proviene de una reprogramación, referencia la cita original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones', to='medical.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CitaReprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='como_anterior', to='medical.cita')),
                ('cita_nueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='como_nueva', to='medical.cita')),
                ('cita_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reprogramaciones', to='medical.cita')),
            ],
        ),
        migrations.CreateModel(
            name='DiaNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_disponibles', to='medical.medico')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('diagnosticos', models.TextField(blank=True, null=True)),
                ('tratamientos', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField(blank=True, default='', null=True)),
                ('archivos', models.FileField(blank=True, null=True, upload_to='consultas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medical.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente')),
            ],
        ),
    ]
