# Generated by Django 5.2.3 on 2025-06-16 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='horario',
            field=models.CharField(choices=[('turno_dia_1', 'Turno Día 1: 7:00 a.m. – 3:00 p.m. (Lun a Vie; Descanso: Sáb y Dom)'), ('turno_dia_2', 'Turno Día 2: 9:00 a.m. – 5:00 p.m. (Mar a Sáb; Descanso: Dom y Lun)'), ('turno_noche_1', 'Turno Noche 1: 3:00 p.m. – 11:00 p.m. (Lun a Vie; Descanso: Sáb y Dom)'), ('turno_noche_2', 'Turno Noche 2: 11:00 p.m. – 7:00 a.m. (Mié a Dom; Descanso: Lun y Mar)')], max_length=20),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente')),
            ],
        ),
    ]
