# Generated by Django 5.2.1 on 2025-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
    ]
