# Generated by Django 5.2.3 on 2025-10-17 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cita_origen',
            field=models.ForeignKey(blank=True, help_text='Si esta cita proviene de una reprogramación, referencia la cita original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones', to='medical.cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='reprogramaciones_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='CitaReprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='como_anterior', to='medical.cita')),
                ('cita_nueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='como_nueva', to='medical.cita')),
                ('cita_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reprogramaciones', to='medical.cita')),
            ],
        ),
    ]
