# Generated by Django 5.2.1 on 2025-10-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_sync_estado_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
