# Generated by Django 5.2.3 on 2025-06-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_medico_horario_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medico'),
        ),
    ]
