# Generated by Django 5.2.1 on 2025-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='genero',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto',
            field=models.CharField(default='sin contacto', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(default='sin direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificacion',
            field=models.CharField(default='2000-01-01', max_length=20),
            preserve_default=False,
        ),
    ]
