# Generated by Django 5.2.1 on 2025-09-05 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_cita_especialidad_alter_cita_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('archivos', models.FileField(blank=True, null=True, upload_to='consultas/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='medical.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente')),
            ],
        ),
    ]
