# Generated by Django 5.2.1 on 2025-11-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_usuario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dianodisponible',
            name='medico',
        ),
        migrations.DeleteModel(
            name='PlantillaCorreo',
        ),
        migrations.DeleteModel(
            name='DiaNoDisponible',
        ),
    ]
