# Generated by Django 5.2.1 on 2025-10-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_dianodisponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantillaCorreo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
