# Generated by Django 5.2.1 on 2025-11-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_remove_dianodisponible_medico_delete_plantillacorreo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=150)),
                ('contenido_principal', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('despedida', models.TextField(default='Atentamente')),
                ('firma', models.TextField(default='Clínica G1')),
                ('informacion_contacto', models.TextField(default='Contacto: 12345678')),
                ('saludo', models.TextField(default='Estimado/a')),
            ],
        ),
        migrations.CreateModel(
            name='DiaNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_disponibles', to='medical.medico')),
            ],
        ),
    ]
