# Generated by Django 5.2.1 on 2025-09-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_consultamedica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultamedica',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medical.cita'),
        ),
    ]
