# Generated by Django 5.2.1 on 2025-09-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('medico', 'Médico'), ('recepcionista', 'Recepcionista'), ('paciente', 'Paciente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
