# Generated by Django 5.2.1 on 2025-09-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_consultamedica_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='observaciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
