# Generated by Django 5.2.3 on 2025-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_consultamedica_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contacto',
            field=models.EmailField(max_length=250),
        ),
    ]
