# Generated by Django 5.2.1 on 2025-09-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_usuario_clave_alter_usuario_rol_and_more'),
        ('medical', '0007_alter_paciente_contacto'),
    ]

    operations = [
    ]
