# Generated by Django 5.2.1 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_merge_20250914_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Médico', 'Médico'), ('Recepcionista', 'Recepcionista'), ('Paciente', 'Paciente')], max_length=20),
        ),
    ]
