# Generated by Django 5.2.1 on 2025-09-15 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('diagnosticos', models.TextField(blank=True, null=True)),
                ('tratamientos', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.paciente')),
            ],
        ),
    ]
