# Generated by Django 5.2.3 on 2025-10-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_plantillacorreo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantillacorreo',
            old_name='cuerpo',
            new_name='contenido_principal',
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='despedida',
            field=models.TextField(default='Atentamente'),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='firma',
            field=models.TextField(default='Clínica G1'),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='informacion_contacto',
            field=models.TextField(default='Contacto: 12345678'),
        ),
        migrations.AddField(
            model_name='plantillacorreo',
            name='saludo',
            field=models.TextField(default='Estimado/a'),
        ),
    ]
