# Generated by Django 5.2.1 on 2025-10-05 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_rename_cuerpo_plantillacorreo_contenido_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='reminder_sent_24',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='reminder_sent_48',
            field=models.BooleanField(default=False),
        ),
    ]
