# Generated by Django 5.2.1 on 2025-10-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_cita_estado_cita_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
