# Generated by Django 5.2.1 on 2025-10-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('user_creation', 'Creación de usuario'), ('user_update', 'Actualización de usuario'), ('user_deletion', 'Eliminación de usuario'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.usuario'),
        ),
    ]
