# Generated by Django 5.2.1 on 2025-11-10 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_accion_alter_auditlog_usuario'),
        ('medical', '0003_usuario_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='usuario',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='usuario_admin',
            field=models.ForeignKey(blank=True, help_text='Usuario del panel admin', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='usuario_sistema',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema clínico', null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.usuario'),
        ),
    ]
