# Generated by Django 5.2.1 on 2025-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('role_change', 'Cambio de rol'), ('user_creation', 'Creación de usuario'), ('user_deletion', 'Eliminación de usuario'), ('user_update', 'Actualización de usuario')], max_length=50),
        ),
    ]
