# Generated by Django 5.2.1 on 2025-10-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_usuario'),
        ('medical', '0014_cita_estado_alter_cita_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.usuario'),
        ),
    ]
