# Generated by Django 5.2.1 on 2025-10-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_accion'),
        ('audit', '0005_alter_auditlog_usuario'),
    ]

    operations = [
    ]
